theme: jekyll-theme-dinky
title: Field matters
description: The first workshop on NLP applications to field linguistics </br> <a href="https://field-matters.github.io/cfp">Call for papers</a></br><a href="https://field-matters.github.io/sharedtask">Shared tasks</a>
github:
  is_project_page: false

